### PR TITLE
feat: new website

### PR DESCRIPTION
**Pull request by hacdias**
License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

### CODE REVIEW

**Comment by 1138-4EB** [comment]
I'm using Firefox on Windows. In the home page, the blue bar on the bottom is rendered outside of the viewable area. It seems that the section with white/gray background takes 100% of the vertical space.

**Comment by hacdias** [comment]
We can change it though.

**Comment by hacdias** [comment]
@1138-4EB try again!

**Comment by 1138-4EB** [comment]
Just a screencast:

fb_home

**Comment by hacdias** [comment]
@1138-4EB not anymore 😛

**Pull request merged**
